[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.ruff]
line-length = 120
select = [
    "E",
    "F",
    "I",
]
